### ISSUE TITLE
rust: Add support to parse Cargo.lock as well

### ISSUE THREAD

**Issue by surajssd** [vbatts/is-archived#2]
I am not sure what is the right thing to see, a Cargo.lock or Cargo.toml but add support for lock file as well.

**Comment by vbatts** [comment]
we might can check some values in the *.lock file, but that would always mean the `Cargo.toml` must also be there.
What additional info might be expected there?

**Comment by surajssd** [comment]
I guess we can look for Cargo.lock first and then fall back to Cargo.toml. Library projects may not have Cargo.lock in there. But I suggest Cargo.lock because it is easier and consistent format.
